### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by zhanglei-workspace** [dss886/BYR-BBS-APP-Release#1]
这个app下载不了啊。

另外，这个外校的可以用吗

**Comment by dss886** [comment]
我这里可以下载啊？可能是因为最近偶尔有墙干扰……
如果不能下载可以去腾讯应用宝下载：http://sj.qq.com/myapp/detail.htm?apkName=cn.byr.bbs.app

需要登录论坛账号才能浏览和回复
